config/routes.rb
Rails.application.routes.draw do

  resources :bands do
    resources :albums, except: [:show]
  end

  resources :albums
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, presence: true
  # validates :recorded, inclusion: { ['true, false'] }

  belongs_to :band

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token
  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by(email: email)
    return @user if @user && @user.is_password?(password)
    nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album
      @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def destroy
    @album = Album.find_by(album_params)
    if @album
      @album.destroy
      render :new
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :recorded, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def login!(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to band_url(@band)
    end
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    if @band
      @band.destroy!
      redirect_to bands_url
    else
      flash[:errors] = ['This band does not exist']
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ['Invalid login!']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to(user_url(@user))
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>Make a Mistake?</h1>
<form action="<%= album_url(@album) %>" method='post'>
  <input type="hidden" name="_method"  value= 'patch'>

<label for="albumtitle">Album Title</label>
<input type="text" name="album[title]" id="albumtitle" value='<%= @album.title %>'>
<br>
<label for="albumyear">Year Recorded
<input type="text" name="album[year]"value='<%= @album.year %>'></label>
<br>
<label for="recordedlive">Recorded Live?</label>
<input type="radio" name="album[recorded]" value='true'<%= @album.recorded == "true" ? "checked" : "" %>> True
<input type="radio" name="album[recorded]" value='false'<%= @album.recorded == "false" ? "checked" : "" %>> False
<br>

<label for="bandid">Band Who Recorded This?</label>
<select name="album[band_id]" id="bandid">
<% Band.find_each do |band| %>
<option
<%= @album.band_id == band.id ? "selected" : "" %>
value='<%=band.id%>'><%=band.name%>
</option>
<%end%>
</select>

<input type="submit" value='ChangeYourPoorAlbum'>
</form>

app/views/albums/new.html.erb
<h1>List a New Album!</h1>
<form action="<%= albums_url %>" method='post'>

<label for="albumtitle">Album Title</label>
<input type="text" name="album[title]" id="albumtitle">
<br>
<label for="albumyear">Year Recorded
<input type="text" name="album[year]"></label>
<br>
<label for="recordedlive">Recorded Live?</label>
<input type="radio" name="album[recorded]" value='true'> True
<input type="radio" name="album[recorded]" value='false'> False
<br>
<select name="album[band_id]" id="bandid">
<% Band.find_each do |band| %>
<option value='<%=band.id%>'><%=band.name%></option>
<%end%>
</select>

<input type="submit" value='Create this Album.'>
</form>

app/views/albums/show.html.erb
<h1>Album Page for: <%= @album.title%> </h1>

<p>Album Title: <%= @album.title%> </p>
<p>Year Recorded: <%= @album.year%> </p>
<% if @album.recorded %>
<p>This album was recorded live.</p>
<% elsif %>
<p>This was a studio recording.</p>
<% end %>

app/views/bands/edit.html.erb
<h1>Change Your Band!</h1>
<form action="<%= band_url(@band) %>" method='post'>
  <input type="hidden" name="_method"  value= 'patch'>

<label for="bandname">Band Name</label>
<input type="text" name="band[name]" id="bandname" value='<%= @band.name %>'>
<input type="submit" value='ChangeYourPoorBand'>
</form>

app/views/bands/index.html.erb
<h1>Look at these bands y'all!</h1>
<% @bands.each do |band| %>
<p><a href="<%= band_url(band) %>"> <%= band.name %></a></p>
<% end %>

app/views/bands/new.html.erb
<h1>Create Your Band!</h1>
<form action="<%= bands_url %>" method='post'>

<label for="bandname">Band Name</label>
<input type="text" name="band[name]" id="bandname">
<input type="submit" value='SignUpYoBand'>
</form>

app/views/bands/show.html.erb
<h1>Look at this cool band!</h1>
<h1> <%= @band.name %> </h1>
<form action="<%= band_url(@band) %>" method="post">
<input type="hidden" name="_method" value="delete">
<input type="submit" value="Delete Band">
</form>
<a href="<%= edit_band_url(@band) %>"> Edit This Band</a>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link
  <head>
    <link href="https://fonts.googleapis.com/css?family=Rozha+One" rel="stylesheet">
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <header>
  <% if current_user.nil? %>
    <%= link_to 'Sign in', new_session_url %>
    <%= link_to 'Sign up', new_user_url %>
  <% else %>
    <%= current_user.email %>
    <%= button_to 'Logout', session_url, method: :delete %>
  <% end %>

  <h1> Welcome to MusicApp: The App that Snaps!</h1>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create New User!</h1>
<form action="<%= users_url %>" method='post'>

<label for="email">Email</label>
<input type="text" name="user[email]" id="email">
<label for="password">Password</label>
<input type="password" name="user[password]" id="password">
<input type="submit" value='SignUp'>
</form>

app/views/users/show.html.erb
<p>How you doing <%= @user.email %>?</p>